Fix other links in main page
MakieOrg/Website pull request #12
Opened 2024-08-01 12:14 UTC by apraga

JSServe -> Bonito
Tyler.jl updated

2024-08-03 11:32 UTC, asinghvi17 requested changes

2024-08-03 11:32 UTC, asinghvi17 commented on docs/index.html
> +                <a class="visited:text-purple-600 text-blue-600" href="https://makieorg.github.io/Tyler.jl/v0.1.4/iceloss_ex" style="" target="_blank" data-jscall-id="65">
```suggestion
                <a class="visited:text-purple-600 text-blue-600" href="https://makieorg.github.io/Tyler.jl/stable/iceloss_ex" style="" target="_blank" data-jscall-id="65">

2024-08-03 11:32 UTC, asinghvi17 commented on src/index.jl
> +            link="https://makieorg.github.io/Tyler.jl/v0.1.4/iceloss_ex",
```suggestion
            link="https://makieorg.github.io/Tyler.jl/stable/iceloss_ex",
```

2024-08-04 16:15 UTC, apraga commented
I've rebased onto the main branch to incorporate Simon's change.

2024-08-04 16:54 UTC, SimonDanisch commented
Thank you!

2024-08-04 16:54 UTC, merged